# Spring Boot application properties
server.port=8080
spring.application.name=oom-example
server.tomcat.max-threads=4

# JVM memory settings
# Set maximum heap size to 512MB (adjust as needed)
# Setting a larger heap size will delay the OOM condition
# This is optional and can be omitted if you want the OOM to happen as soon as possible
java.security.egd=file:/dev/./urandom
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
# -Xmx512m

# JVM memory settings
# spring-boot.run.jvmArguments=-Xmx75m

# Logging settings
logging.file=myapp.log
logging.level.root=ERROR

# Logback specific settings
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n